name: persian_calendar
description: A complete Persian calendar library for Dart, supporting Jalali, Gregorian, Islamic, and Nepali calendars.
version: 1405.04.22
homepage: https://github.com/syedmohdbarzgar/persian_calendar
repository: https://github.com/syedmohdbarzgar/persian_calendar
issue_tracker: https://github.com/syedmohdbarzgar/persian_calendar/issues

environment:
  sdk: ^3.12.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6